global: {}
receivers:
  - name: default-receiver
    slack_configs:
      - channel: "#monitoring"
        send_resolved: true
        api_url: "${ALERTMANAGER_SLACK_URL}"
route:
  group_wait: 10s
  group_interval: 5m
  receiver: default-receiver
  repeat_interval: 3h
