{
 "title": "Traefik",
 "description": "Traefik status.",
 "tags": [
  "traefik",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests per second (RPS)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total[1m])) by (method)"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(traefik_entrypoint_request_duration_seconds_sum[1m])) by (method)"
    }
   ]
  },
  {
   "title": "Traffic by Pod",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total[5m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}