kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admins-users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:

  # Grant permissions to administrator
  - kind: User
    name: ${ADMIN_USR}

  # Grant permissions to the system deployer (GCP service account)
  - kind: User
    name: deployer@arikkfir.iam.gserviceaccount.com
---
