apiVersion: v1
kind: Secret
metadata:
  namespace: cert-manager
  name: cloudflare-api-key-secret
type: Opaque
data:
  api.key: "${CLOUDFLARE_TOKEN}"
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: cluster-issuer
spec:
  acme:
    server: ${LETSENCRYPT_URL}
    email: ${LETSENCRYPT_ACCOUNT_EMAIL}
    privateKeySecretRef:
      name: cloudflare-cluster-issuer-account-key
    dns01:
      providers:
        - name: cloudflare
          cloudflare:
            email: ${CLOUDFLARE_EMAIL}
            apiKeySecretRef:
              name: cloudflare-api-key-secret
              key: api.key
---
