apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: kubewatch
  labels:
    app: kubewatch
    component: rbac
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kubewatch
  labels:
    app: kubewatch
    component: rbac
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
      - services
      - deployments
      - replicationcontrollers
      - replicasets
      - daemonsets
      - persistentvolumes
    verbs:
      - list
      - watch
      - get
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - deployments/scale
      - replicasets
      - replicasets/scale
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - deployments/scale
      - replicasets
      - replicasets/scale
      - replicationcontrollers/scale
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  namespace: kube-system
  name: kubewatch
  labels:
    app: kubewatch
    component: exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubewatch
subjects:
  - kind: ServiceAccount
    namespace: kube-system
    name: kubewatch
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: kubewatch
  labels:
    app: kubewatch
    component: config
data:
  .kubewatch.yaml: |
    handler:
      slack:
        enabled: true
        channel: "#general"
        token: "${KUBEWATCH_SLACK_TOKEN}"
    resource:
      deployment: true
      replicationcontroller: false
      replicaset: false
      daemonset: true
      services: true
      pod: true
      job: true
      persistentvolume: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: kubewatch
  labels:
    app: kubewatch
    component: exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubewatch
      component: exporter
  template:
    metadata:
      labels:
        app: kubewatch
        component: exporter
    spec:
      serviceAccountName: kubewatch
      containers:
        - name: kubewatch
          image: bitnami/kubewatch:0.0.4
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 384Mi
          volumeMounts:
            - name: config
              mountPath: /opt/bitnami/kubewatch/.kubewatch.yaml
              subPath: .kubewatch.yaml
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: kubewatch
