namespace: ""
handler:
  slack:
    token: "${KUBEWATCH_SLACK_TOKEN}"
    channel: "#monitoring"
resource:
  deployment: true
  replicationcontroller: false
  replicaset: false
  daemonset: true
  services: true
  pod: true
  job: true
  persistentvolume: true
