apiVersion: v1
kind: Namespace
metadata:
  name: kubewatch
  labels:
    app: kubewatch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kubewatch
  name: kubewatch
  labels:
    app: kubewatch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kubewatch
  labels:
    app: kubewatch
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
      - services
      - deployments
      - replicationcontrollers
      - replicasets
      - daemonsets
      - persistentvolumes
    verbs:
      - list
      - watch
      - get
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - deployments/scale
      - replicasets
      - replicasets/scale
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - deployments/scale
      - replicasets
      - replicasets/scale
      - replicationcontrollers/scale
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubewatch
  labels:
    app: kubewatch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubewatch
subjects:
  - kind: ServiceAccount
    name: kubewatch
    namespace: kubewatch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kubewatch
  name: kubewatch
  labels:
    app: kubewatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubewatch
  template:
    metadata:
      labels:
        app: kubewatch
    spec:
      serviceAccountName: kubewatch
      containers:
        - name: kubewatch
          image: bitnami/kubewatch:0.0.4
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 384Mi
          volumeMounts:
            - name: config
              subPath: .kubewatch.yaml
              mountPath: /opt/bitnami/kubewatch/.kubewatch.yaml
      volumes:
        - name: config
          configMap:
            name: config
---
