apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
  labels:
    app: prometheus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: prometheus
  name: prometheus
  labels:
    app: prometheus
    component: rbac
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
  labels:
    app: prometheus
    component: rbac
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
      - ingresses
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
    resources:
      - ingresses/status
      - ingresses
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
  labels:
    app: prometheus
    component: rbac
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  namespace: prometheus
  name: alertmanager
  labels:
    app: prometheus
    component: alertmanager
spec:
  secretName: alertmanager-crt
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer
  commonName: alerts.prometheus.${GKE_CLUSTER_NAME}.kfirs.com
  dnsNames:
    - alerts.prometheus.${GKE_CLUSTER_NAME}.kfirs.com
  acme:
    config:
      - dns01:
          provider: cloudflare
        domains:
          - alerts.prometheus.${GKE_CLUSTER_NAME}.kfirs.com
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  namespace: prometheus
  name: server
  labels:
    app: prometheus
    component: server
spec:
  secretName: server-crt
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer
  commonName: prometheus.${GKE_CLUSTER_NAME}.kfirs.com
  dnsNames:
    - prometheus.${GKE_CLUSTER_NAME}.kfirs.com
  acme:
    config:
      - dns01:
          provider: cloudflare
        domains:
          - prometheus.${GKE_CLUSTER_NAME}.kfirs.com
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: prometheus
  name: ingress
  annotations:
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    traefik.ingress.kubernetes.io/whitelist-source-range: "${WHITELISTED_CIDR}"
  labels:
    app: prometheus
    component: ingress
spec:
  rules:
    - host: alerts.prometheus.${GKE_CLUSTER_NAME}.kfirs.com
      http:
        paths:
          - backend:
              serviceName: alertmanager
              servicePort: http
    - host: prometheus.${GKE_CLUSTER_NAME}.kfirs.com
      http:
        paths:
          - backend:
              serviceName: server
              servicePort: http
  tls:
    - hosts:
        - alerts.prometheus.${GKE_CLUSTER_NAME}.kfirs.com
      secretName: alertmanager-crt
    - hosts:
        - prometheus.${GKE_CLUSTER_NAME}.kfirs.com
      secretName: server-crt
