# TODO: keepTrailingSlash = true
logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

[entryPoints]

    [entryPoints.http]
    address = ":80"
    compress = true

    [entryPoints.https]
    address = ":443"
    compress = true

        [entryPoints.https.tls]
        sniStrict = true

    [entryPoints.admin]
    address = ":8080"
    compress = true

[kubernetes]

    [kubernetes.ingressEndpoint]
    publishedService = "traefik/service"

[traefikLog]
format = "json"

[accessLog]
format = "json"
bufferingSize = 0

    [accessLog.fields]
    defaultMode = "keep"

        [accessLog.fields.headers]
        defaultMode = "keep"

[api]
entryPoint = "admin"
dashboard = true

    [api.statistics]
    recentErrors = 10

[metrics]

    [metrics.prometheus]
    entryPoint = "admin"
